Edit service list (fixes #11)
openBackhaul/Linkid2LtpTranslator pull request #12
Opened 2022-09-21 14:18 UTC by tileh

2022-09-21 14:38 UTC, xiidoz commented
I'd like to review.

2022-10-05 11:27 UTC, xiidoz requested changes

2022-10-05 11:27 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +            uuid: l2lt-1-0-0-op-s-is-001
What will this service return, the whole air-interface-LTP- object or only its UUID? If it's only the UUID, I'd rename the service to represent that.

2022-10-05 11:27 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +
There's random whitespace.

2022-10-05 11:27 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +      own-application-name: Linkid2LtpTranslator
Maybe LinkId2LtpTranslator would be more fitting, as it's the link ID instead of linkid ;)

2022-10-05 12:00 UTC, tileh commented on LinkId2Ltp+services.yaml
> +      own-application-name: Linkid2LtpTranslator
This may be true, but the costs of changing the name outweighs the benefit in my opinion (+ this name would be larger than the maximum of four words for application names)

2023-03-06 08:36 UTC, xiidoz requested changes
Please make sure to use the most recent published ApplicationPattern (currently v2.0.1). And also, please check your linter, as I haven't marked the YAML syntax errors.
After adressing the issues I found and if not already done so, please get an ok from @kmohr-soprasteria, especially regarding the called services on the MWDI.

2023-03-06 08:36 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +    tpc-server:
Typo

2023-03-06 08:36 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +        release-number: 1.0.0
Outdated. Please check ApplicationPattern v2.0.1 for current config.

2023-03-06 08:36 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +        release-number: 1.0.0
Outdated. Please check ApplicationPattern v2.0.1 for current config.

2023-03-06 08:36 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +        release-number: 1.0.0
Outdated. Please check ApplicationPattern v2.0.1 for current config.

2023-03-06 08:36 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +        release-number: 1.0.0
Outdated. Please check ApplicationPattern v2.0.1 for current config.

2023-03-06 08:36 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +        release-number: 1.0.0
Outdated. Please check ApplicationPattern v2.0.1 for current config.

2023-03-06 08:36 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +        release-number: 1.0.0
Outdated. Please check ApplicationPattern v2.0.1 for current config.

2023-03-06 08:36 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +        release-number: 1.0.0
Outdated. Please check ApplicationPattern v2.0.1 for current config.

2023-03-06 08:36 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +          - service-name: /v1/start-application-in-generic-representation
start-application-in-generic-representation is a basic service, not individual.

2023-03-06 08:36 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +          - service-name: /v1/register-yourself
With ApplicationPattern v2.0.0 `service-name` was renamed to `operation-name`

2023-03-06 08:36 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +            uuid: l2lt-1-0-0-op-s-bs-004
Basic service `/docs` is missing.

2023-03-06 08:36 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +      uuid: l2lt-1-0-0-tcp-s-bm-000
Differentiation between TLS and non-TLS is missing.

2023-03-06 08:36 UTC, xiidoz commented on LinkId2Ltp+services.yaml
> +        uuid: l2lt-1-0-0-tcp-c-bm-or-1-0-0-000
`tcp-client` is lacking `remote-protocol`.

2023-05-22 10:54 UTC, xiidoz approved these changes
LGTM! :)

2023-05-31 14:55 UTC, xiidoz submitted a review, later dismissed

2023-06-02 10:12 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
> +                - service-name: /v1/register-yourself
hier muss überall **operation-name** stehen, statt **service-name**

2023-06-02 10:47 UTC, kmohr-soprasteria requested changes

2023-06-02 10:47 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
> +    tcp-server:
tcp-server muss der Vorlage aus dem AppPattern folgen:

```
  tcp-server:
    - description: Without TLS layer
      local-protocol: http
      own-ip-address: 1.1.4.8
      own-tcp-port: 4008
      uuid: l2lt-1-0-0-tcp-s-000
    - description: With TLS layer
      local-protocol: https
      own-ip-address: 1.2.4.8
      own-tcp-port: 4208
      uuid: l2lt-1-0-0-tcp-s-001
```

2023-06-02 10:47 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
> +    - http-client:
bei der ersten Version (1.0.0) einer Applikation muss beim NewRelease auch noch mal (1.0.0) angegeben werden.
Du musst hier nur die Release-number zu 1.0.0 ändern; die uuids ist korrekt (wäre die relNum tatsächlich 1.0.1, müsste in der uuid hinten auch ...nr-1-0-1 stehen)

2023-06-02 10:47 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
> +                  - service-name: /v1/provide-list-of-mwdi-mount-names
den Service für die mount-name-Liste gibt es im MWDI nicht mehr, das muss ersetzt werden durch:
          - operation-name: /?fields=node(node-id)
            uuid: l2lt-1-0-0-op-c-is-mwdi-1-0-0-000

2023-06-02 10:47 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
> +                  - service-name: /node={mount-name}/yang-ext:mount/core-model-1-4:control-construct?content=config&fields=logical-termination-point(layer-protocol(layer-protocol-name);uuid;name(valu
Bei den Query-Parametern wird nur der fields-Filter unterstützt,
d.h. in deinem Service-Name entfällt der Teil "content=config&"

2023-06-02 10:47 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
> +                  # get list of mount names to iterate through
bei beiden services muss **operation-name** stehen, statt **service-name**

2023-06-05 13:10 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
> +                  - service-name: /node={mount-name}/yang-ext:mount/core-model-1-4:control-construct?content=config&fields=logical-termination-point(layer-protocol(layer-protocol-name);uuid;name(valu
in absehbarer Zukunft wird nur der Fields-Filter unterstützt. Allerdings wird es da vielleicht irgendwann nochmal eine zweite Version von geben, bei der man auch nach ganz bestimmten Werten suchen kann, also z.B. statt alle gefundenen Records von _?fields=logical-termination-point(layer-protocol(layer-protocol-name);uuid;name(value-name;value))_ zurückzugeben, könnte man auf eine bestimmte uuid filtern: _?fields=logical-termination-point(layer-protocol(layer-protocol-name);_**wo uuid = xyz**_;name(value-name;value))_ (natürlich mit einem gültigen Format)

2023-06-05 13:13 UTC, tileh commented on spec/Linkid2LtpTranslator+services.yaml
> +                  - service-name: /node={mount-name}/yang-ext:mount/core-model-1-4:control-construct?content=config&fields=logical-termination-point(layer-protocol(layer-protocol-name);uuid;name(valu
Ah stimmt, das reicht ja sogar schon. Ok dann passt das, vielen Dank :)

2023-08-31 10:53 UTC, kmohr-soprasteria requested changes
s. inline-Code-Kommentare

2023-08-31 10:53 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
> +    operation-servers:
bitte hier nochmal die Einrückungen überprüfen.
Im AppPattern-Template sind weniger Leerzeichen, hier ist die Anzahl anscheinend immer verdoppelt.
(Ich vermute, dass dein VSCode als Tab 4 statt 2 Leerzeichen eingestellt hat, das kann man ganz einfach in den Einstellungen vom VSC ändern...)

2023-08-31 10:53 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
> +        uuid: l2lt-1-0-0-http-s-bm-000
uuid hier ohne "bm-", also nur l2lt-1-0-0-http-s-000

2023-08-31 10:53 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
>  clients:
wenn du ElasticSearch benutzen willst, muss auch immer ein Index-Alias angegeben werden, mit dem der korrekte Abschnitt der Datenbank identifiziert werden kann. s. [hier](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/TestingApplications/Infrastructure/SdnLaboratory/FakeAddresses/IndexAliases.md): das wäre der Index 5
also: 
```
  - http-client:
      application-name: ElasticSearch
      release-number: 1.0.0
      uuid: l2lt-1-0-0-http-c-es-1-0-0-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.3.15
      tcp-port: 3015
      uuid: l2lt-1-0-0-tcp-c-es-1-0-0-000
    elasticsearch-client:
      uuid: l2lt-1-0-0-es-c-es-1-0-0-000
      index-alias: 5

2023-08-31 10:53 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
> +          uuid: l2lt-1-0-0-http-c-is-mwdi-1-0-0-000
uuid ohne is:
uuid: l2lt-1-0-0-http-c-mwdi-1-0-0-000

2023-08-31 10:53 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
> +          uuid: l2lt-1-0-0-tcp-c-is-mwdi-1-0-0-000
uuid analog ohne is
uuid: l2lt-1-0-0-tcp-c-mwdi-1-0-0-000

2023-08-31 10:53 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
> +                  - operation-name: /?fields=node(node-id)
MWDI v1.0.0 ist jetzt offiziell veröffentlicht und in der Zwischenzeit hat sich an der ServiceList vom MWDI viel getan. D.h. deine operation-clients sind nicht mehr aktuell. (Deine Uuids können aber so bleiben, weil die Sequenznummern beziehen sich ja nicht auf die uuids aus dem MWDI, sondern auf die Nummerierung der operation-clients innerhalb deiner Applikation).

Die Mount-name-Liste wird jetzt statt von `/?fields=node(node-id)` von folgendem MWDI-Service bereitgestellt:
```
        - operation-name: /v1/provide-list-of-connected-devices
          uuid: mwdi-1-0-0-op-s-is-010
```

2023-08-31 10:53 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
> +                  - operation-name: /node={mount-name}/yang-ext:mount/core-model-1-4:control-construct?fields=logical-termination-point(layer-protocol(layer-protocol-name);uuid;name(value-name;value)
es gibt jetzt 2 getrennte Service-Bereiche: `*domain=cache*` (Daten aus Cache lesen) und `*domain=live*` (Daten statt aus dem Cache vom Controller neu abfragen, wobei der Cache auch aktualisiert wird.)

Du musst also folgenden neuen operation-client benutzen:
```
        - operation-name: /core-model-1-4:network-control-domain=cache/control-construct={mount-name}
          uuid: mwdi-1-0-0-op-s-is-100
```
und hinten noch deinen Fields-Filter dranhängen, also:
```
- operation-name: /core-model-1-4:network-control-domain=cache/control-construct={mount-name}?fields=logical-termination-point(layer-protocol(layer-protocol-name);uuid;name(value-name;value))
```

2023-08-31 13:37 UTC, tileh commented on spec/Linkid2LtpTranslator+services.yaml
> +    operation-servers:
Ich glaube, das lag sogar am GitHub-Linter, der so viele Einrückungen wollte

2023-09-04 14:59 UTC, kmohr-soprasteria requested changes

2023-09-04 14:59 UTC, kmohr-soprasteria commented on spec/Linkid2LtpTranslator+services.yaml
> +          # get list of mount names to iterate through
die uuids stimmen nicht.
In deiner Applikation müssen alle uuids immer mit l2lt-<versionsnummer> anfangen.
Siehe Bsp ApplicationLayerTopology:
l2lt-1-0-0-op-c-bm-alt-2-0-1-000
- vorne kommt deine Applikation: "l2lt-1-0-0-"
- dann die Protokoll- und Service-Typ-Info: "op-c-bm-"
- dann die Abkürzung + Versionsnummer von der App, die du ansprechen willst: "alt-2-0-1"
- und dann noch die Sequenznummer: die übernimmst du nicht von der angesprochenen App, sondern vergibst du anhand deiner App

Also hier: l2lt-1-0-0-op-c-is-mwdi-1-0-0-000 und  l2lt-1-0-0-op-c-is-mwdi-1-0-0-001

2023-09-15 09:10 UTC, merged